Repository runelite/runelite-discord-bot, pull requests merged in 2020-10, with the labels that each got.

#50 Fix checking for file extensions
  lib/security.js
Labels: bug

#51 Add info command and user count to join/leave messages
  lib/app.js
  lib/commands.js
Labels: enhancement

#49 Make Twitch announcements more stable
  lib/app.js
  lib/commands.js
  lib/twitch.js
Labels: bug, enhancement

#52 Add matching for first longest match when typing custom commands
  lib/commands.js
Labels: enhancement

#53 Add wiki search command
  lib/commands.js
Labels: feature-request

#54 Improve audit logging
  lib/app.js
  lib/common.js
  lib/security.js
Labels: enhancement

#55 Use GitHub login instead of name in !ghinfo
  lib/commands.js
Labels: bug

#56 Add permission checks for !info commands and audit log
  lib/commands.js
  lib/common.js
Labels: bug

#57 Remove old promise handling
  lib/app.js
Labels: bug

#58 Fix sorting when matching commands
  lib/commands.js
Labels: bug

#59 Show command help only if there is no exact match
  lib/commands.js
Labels: enhancement

#60 lib: Fix style violation
  lib/commands.js
Labels: bug

#61 Switch to GitHub actions
  .github/workflows/build.yml
  .travis.yml
Labels: enhancement

#62 Fix npm run build
  .github/workflows/build.yml
Labels: bug
