Repository runelite/runelite-discord-bot, pull requests merged in 2021-09, with the labels that each got.

#82 Fix !phwhois error messages
  lib/commands.js
Labels: bug

#83 Use Discord slash command API for commands
  lib/app.js
  lib/blocked.js
  lib/commands.js
  lib/commands/command.js
  lib/commands/filter.js
  lib/commands/gh.js
  lib/commands/ghauth.js
  lib/commands/ghsearch.js
  lib/commands/index.js
  lib/commands/notice.js
  lib/commands/whois.js
  lib/commands/wikisearch.js
  lib/common.js
  lib/config.js
  lib/contributors.js
  lib/db.js
  lib/flag.js
  lib/notice.js
  lib/security.js
  lib/twitch.js
  package-lock.json
  package.json
Labels: enhancement, feature-request

#88 Limit content of message to 500 chars for mod log replies
  lib/security.js
Labels: bug

#89 Add dual mode with ! for custom commands
  lib/app.js
  lib/config.js
Labels: enhancement

#90 Fix ban logs, fix messageUpdate filtering
  lib/app.js
  lib/commands/command.js
  lib/commands/index.js
  lib/security.js
Labels: bug

#91 Use reason from auditEntry as reason from guildBan is not working
  lib/app.js
Labels: bug

#92 Add missing checks for DMs/guild messages
  lib/app.js
  lib/notice.js
  lib/security.js
Labels: bug
